approve_by_comment: true
approve_regex: ^(Approved|:\+1:)
reject_regex: ^(Rejected|:-1:)
author_approval: ignored
reset_on_push: true
reviewers:
  members:
  - rawlinc
  - rawlink
  name: default
  required: 1
